version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"